# LaTeX build workflow, to ensure the PDF will build on any device.
# Based on the marketplace action found here: https://github.com/marketplace/actions/github-action-for-latex
name: Build LaTeX Docs
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Compile LaTeX Executive Summary
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ./report/executive_summary.tex
      
      - name: Compile LaTeX Extended Report
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ./report/extended_report.tex